import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { VehicleProvider } from "@/context/VehicleContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <VehicleProvider>
        <body className={inter.className}>{children}</body>
      </VehicleProvider>
    </html>
  );
}
